# Generated by Django 5.1.1 on 2024-09-18 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name']},
        ),
    ]
