# Generated by Django 5.1.1 on 2024-09-21 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file_path',
            field=models.FileField(upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
